security:
    # Configuration des hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # Configuration des providers d'utilisateurs
    providers:
        # utilisé pour charger les utilisateurs depuis la base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # Configuration du formulaire de connexion
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password
                default_target_path: home # Redirection après connexion réussie

            # Configuration de la déconnexion
            logout:
                path: app_logout
                target: app_login # Redirection après déconnexion

            # Mémoriser l'utilisateur (optionnel)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    # Contrôle d'accès
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: ^/, roles: ROLE_USER } # Bloquer l'accès à toutes les pages pour les utilisateurs non connectés